# Generated by Django 3.0.3 on 2020-03-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20200304_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='created_on',
            new_name='posted_on',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='created_on',
            new_name='posted_on',
        ),
    ]
