# Generated by Django 3.0.3 on 2020-03-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20200304_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='posted_on',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='posted_on',
            new_name='posted_at',
        ),
    ]
