# Generated by Django 3.0.3 on 2020-03-29 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20200320_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='bump_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
