# Generated by Django 3.0.3 on 2020-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_thread_bump_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
