# Generated by Django 3.0.3 on 2020-03-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('attach', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachement',
            new_name='Attachment',
        ),
    ]
