# Generated by Django 3.0.3 on 2020-03-25 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0003_attachment_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='upload_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='attachment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['upload_token'], name='attach_atta_upload__a92c7b_idx'),
        ),
    ]
