# Generated by Django 3.0.3 on 2020-03-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0005_auto_20200325_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='complete',
        ),
    ]
