# Generated by Django 3.0.3 on 2020-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='message',
            field=models.TextField(max_length=6000, verbose_name='Message'),
        ),
    ]
